
GET mongodb://127.0.0.1:27017/Newsletter-Subscription Content-Type: application/json
{
  "email":"222",
  "password":"sss"
}

###

POST http://localhost:3000/login  Content-Type: application/json

{
    "fname": "33",
    "lname": "33",
    "email": "33",
    "password": "33",
  }